# Configs for pwills.com

title: "Learning Jekyll"
name: "Jekyll base site based on pwills.com"
email: example@lorumpbsom.com
url: ""
repository: ""
blogActive: true

include:
  - _pages
  - assets
  - index.html
exclude:
  - TODO.md
  - README.md
  - "*.org"
  - "*ltximg*"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"

# settings for author profile
author:
  name   : "Anna Klis"
  avatar : "/assets/images/anna.jpg"
  bio    : "My name is Anna Klis, and I am an Associate Professor of Economics at Northern Illinois University."
  location: "DeKalb, Illinois,"
  github : 
  linkedin: https://www.linkedin.com/in/anna-klis-1337a150/
  email  : 


# # comments by disqus
comments:
  provider: "disqus"
  disqus:
    shortname: "pwills-com"

analytics:
  provider: "google"
  google:
    tracking_id: "UA-116208936-1"


# pagination for blog page
paginate: 10 # number of posts to show
paginate_path: /page:num/

# default YAML front matter
defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      mathjax: true
      author_profile: true
      class: wide
      title: " "
      title_separator: "|"
  # posts
  - scope:
      type: posts
    values:
      toc: true
      toc_label: "Contents"
      read_time: false
      comments: true
  # portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      author_profile: false
      excerpt: ""
      sidebar:
        nav: "portfolio"

# collections
collections:
  portfolio:
    output: true
